name: Every 15 Minutes Trigger

on:
  schedule:
    # Runs every 15 minutes
    - cron: '*/15 * * * *'

jobs:
  run-task:
    runs-on: ubuntu-latest
    steps:
      - name: Example step
        run: echo "This workflow runs every 15 minutes"
